name: gen_art_canvas
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.2
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  widgetbook: ^3.3.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-light.ttf
          weight: 300
