name: gen_art_canvas
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  firebase_core: ^2.15.1
  equatable: ^2.0.5
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
