// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnVNdXmANwswuGxBoLF1q3zID4Q-U9qow',
    appId: '1:135263320114:web:d0fe349ef280e022b6a42b',
    messagingSenderId: '135263320114',
    projectId: 'genartcanvas',
    authDomain: 'genartcanvas.firebaseapp.com',
    storageBucket: 'genartcanvas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQdWaYp6cWAPok3HmH8Jg4tP1mEswPuYM',
    appId: '1:135263320114:android:65cc310ef5b8752fb6a42b',
    messagingSenderId: '135263320114',
    projectId: 'genartcanvas',
    storageBucket: 'genartcanvas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP5-J5QUw07GYXUUO0yVrPgd0pEUAEXpk',
    appId: '1:135263320114:ios:24e4b40611bd72dcb6a42b',
    messagingSenderId: '135263320114',
    projectId: 'genartcanvas',
    storageBucket: 'genartcanvas.appspot.com',
    iosBundleId: 'com.roaakdm.genArtCanvas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP5-J5QUw07GYXUUO0yVrPgd0pEUAEXpk',
    appId: '1:135263320114:ios:cda09f39ce014b95b6a42b',
    messagingSenderId: '135263320114',
    projectId: 'genartcanvas',
    storageBucket: 'genartcanvas.appspot.com',
    iosBundleId: 'com.roaakdm.genArtCanvas.RunnerTests',
  );
}
